version: '3'
services:
  confluence:
    container_name: jira-confluence
    image: atlassian/jira-software
    volumes:
      - ./jira_data:/var/atlassian/jira
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    container_name: jira-mysql
    image: mysql:8.0
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=jira
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=1234
    ports:
      - 3307:3306

volumes:
  jira_data:
  mysql_data: